### ISSUE TITLE
std::ifstream interface

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/pragzip#16]
It would be nice to have std::ifstream like interface to .gz and .bz files...

**Comment by mxmlnkn** [comment]
I think this could be done similarly to [zfstream](https://github.com/madler/zlib/blob/master/contrib/iostream3/zfstream.h) and might be suited for a community contribution because it should not require modifying any internal code, simply using the read/seek methods of ParallelGzipReader should theoretically be sufficient.

In the short term, I probably will be busy finishing two other features and preparing for the presentation of pragzip at HPDC '23, for which I have uploaded the author's version [here](https://github.com/mxmlnkn/indexed_bzip2/blob/develop/results/paper/Knespel%2C%20Brunst%20-%202023%20-%20Rapidgzip%20-%20Parallel%20Decompression%20and%20Seeking%20in%20Gzip%20Files%20Using%20Cache%20Prefetching.pdf).

**Comment by mxmlnkn** [comment]
Thanks for the feedback and sorry for getting offtopic.

I have implemented this feature request in this commit:
https://github.com/mxmlnkn/indexed_bzip2/commit/835293d8c935994ca144a827c4b3a5cd4650f336

As the tests comment at some places, the `std::istream` interface is subtly different at corners I didn't like. For example, `FileReader::seek` automatically clears the EOF flag while this is not the case for `std::istream`. And even when EOF has been encountered `FileReader::tell` returns the file size, while this is not the case for `std::istream`.

**Comment by mxmlnkn** [comment]
Feel free to reopen the issue if there are problems. I have closed it because it has been merged.
